### ISSUE TITLE
Class name change in Ceylon 1.2.3

### ISSUE THREAD

**Issue by FroMage** [vert-x3/vertx-lang-ceylon#12]
This is just a heads-up for when you upgrade to Ceylon 1.2.3, since you use the `ModuleSpec` class, it has changed name from `com.redhat.ceylon.common.tools.ModuleSpec` to `com.redhat.ceylon.common.ModuleSpec` (promoted one level up). Hope this will help with the transition.

**Comment by vietj** [comment]
we are planning a 3.3.3 release soon - when is Ceylon 1.2.3 released ?

**Comment by FroMage** [comment]
Are you not on ceylon-core? Should be in the next 2-3 weeks.

**Comment by gavinking** [comment]
I believe that this was already fixed.

**Comment by gavinking** [comment]
@FroMage @vietj you should be able to close this.
