### ISSUE TITLE
running ceylon module with 'vertx run'

### ISSUE THREAD

**Issue by gavinking** [vert-x3/vertx-lang-ceylon#21]
There are multiple problems with using `vertx run` and Ceylon:

First, Ceylon support is not enabled by default (!) and this is not mentioned in the Vert.x documentation. Instead it is mentioned [here][instructions]. But it's unreasonable to expect people to know to look for it there.

Second, when `vertx` is installed via Homebrew, there is no `vertx-stack.json` file installed, so the [instructions] don't actually work in that case.

Finally, it seems that in the latest release, `vertx run` simply doesn't work with Ceylon modules at all, even after running `vertx resolve`. This command:

    vertx run ceylon:examples.core.http.simple.server/1.0.0

Results in this error:

    java.lang.ClassNotFoundException: examples.core.http.simple.server/1.0.0

[instructions]: https://github.com/vert-x3/vertx-examples/blob/master/ceylon/README.adoc

**Comment by gavinking** [comment]
> Finally, it seems that in the latest release, `vertx run` simply doesn't work with Ceylon modules at all, even after running `vertx resolve`. 

OK, that's not right. The problem was that I have to run `vertx resolve` from within my Vert.x installation directory, which is not mentioned in the instructions, and doesn't even seem to be properly documented here:

 <http://vertx.io/docs/vertx-stack-manager/stack-manager/#_launching_the_resolution>

**Comment by gavinking** [comment]
@cescoffier @vietj I think it's a bug in `vertx resolve` that it will happily download everything into my project's `lib` directory without telling me something is wrong.

**Comment by gavinking** [comment]
I also think it's a bug that the `vertx` homebrew installation doesn't include a `vertx-stack.json` file. I'm not sure where I should report that one.

**Comment by vietj** [comment]
report it on the vert-x3/vertx-stack project
