### ISSUE TITLE
use static methods instead of companion objects

### ISSUE THREAD

**Issue by gavinking** [vert-x3/vertx-lang-ceylon#22]
The "companion object" pattern is a scala-ism, and is not idiomatic in Ceylon. Currently, all the Vert.x APIs use companion objects as a mapping for Java `static` methods.

This is no longer necessary, since Ceylon has had static methods since version 1.3.1.

This change should significantly simplify the code generator.

**Comment by vietj** [comment]
does ceylon compiler supports Java 8 static interface methods ?

**Comment by gavinking** [comment]
No, not yet.

**Comment by vietj** [comment]
that's a blocker as we generate interface (to handle multiple inheritance)

**Comment by gavinking** [comment]
Oh really? As far as I can see you actually always generate classes in the Ceylon API.

**Comment by gavinking** [comment]
For example, `Router`, `JDBCClient`, `Future`, `BodyHandler` are all classes in Ceylon (though they are indeed interfaces in the Java API).

**Comment by gavinking** [comment]
@vietj I have added experimental support for [static interface methods](https://github.com/ceylon/ceylon/issues/7136) to Ceylon.
