### ISSUE TITLE
HttpServer.requestHandler() accepts null

### ISSUE THREAD

**Issue by gavinking** [vert-x3/vertx-lang-ceylon#3]
For no readily-apparent reason, the parameter of `HttpServer.requestHandler()` is of optional type, meaning it accepts `null`.

I can't imagine what motivation I might have for setting the request handler to `null`, except for the desire to get a `java.lang.IllegalStateException`.

Worse, it means that the type of the request handler parameter (`HttpServerRequest`) can't be inferred by Ceylon, so I have to write:

```ceylon
    server.requestHandler((HttpServerRequest request) {
        ...
    });
```

Instead of just:

```ceylon
    server.requestHandler((request) {
        ...
    });
```

So I think it's clear that the parameter type should be made non-optional here.

**Comment by vietj** [comment]
We can change the request handler to be non nullable, however the thing is that it is possible to set a null handler on a server although most of the time no null handlers will set.

**Comment by gavinking** [comment]
@vietj is it ever *useful* to set a null handler?

**Comment by vietj** [comment]
in this case I think it is not, so I will make the change in vertx core.

**Comment by gavinking** [comment]
Great, thanks :)

**Comment by vietj** [comment]
just for my understanding, I don't understand why:

```
shared void setHandler(Anything<String>? handler) { ... }
```

prevents to infer the String type when a function is passed.

My reasoning is that if a function is passed (and not null) then it has to have String as argument.

**Comment by gavinking** [comment]
@vietj I guess you're using some knowledge about the _disjointness_ of `Null` and `Callable` there, that the type arg inference algorithm doesn't use.

Perhaps it could.

**Comment by vietj** [comment]
https://github.com/eclipse/vert.x/commit/bb44eb6ff024a338da6824da7169a324cfc87954

**Comment by gavinking** [comment]
@vietj FTR, the typechecker now does the reasoning you suggest when inferring parameter types.
